"""
DATA TYPES
INTEGER
STRING 
BOOLEAN
FLOAT
NONE

HOW TO KNOW THE TYPE USED IN A PROGRAMMNING LANGUAGE
PRINT(TYPE(AGE))
PRINT(TYPE(PI))
PRINT(TYPE(COMPLEX_NUM))
PRINT(TYPE(A))
PRINT(TYPE(NAME))
"""